notifications:
  email:
    recipients:
      - rich@flatcap.org
    on_success: change
    on_failure: always

sudo: required
dist: trusty

language: c
compiler: gcc
cache: ccache

addons:
  apt:
    packages:
#     - libslang2-dev

env:
    # Default config
  - OPTS=""
    # Enable components that default to 'off'
  - OPTS="--enable-sidebar"
    # Test SLANG (not default Curses)
# - OPTS="--with-slang --enable-sidebar"

before_script:
  - ccache -z
  - autoreconf -i

script:
  - ./configure $OPTS
  - make
  - ./mutt -v

after_script:
  - ccache -s

